version: "3.1"
services:

  app-service:
    build: service
    container_name: node-service

  webserver:
    image: nginx:latest
    container_name: webservice-dopa
    working_dir: /usr/src/app
    volumes:
        - ./docker-service/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - postgres
      - app-service

  postgres:
    image: postgres:latest
    container_name: database-dopa
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwordNaja
      POSTGRES_DB: test-dopa
  
  redis:
    image: redis:5.0.0
    ports:
      - "6379:6379"
    volumes:
      - ./docker-service/redis/redis.conf:/etc/redis/redis.conf